[project]
name = "twingraph"
version = "0.1.0"
description = "This package provides tools for predictive modeling workflows, including (a) infrastructure provisioning, (b) graph orchestration and (c) recording workflow artifacts for repeatability and auditability."
readme = "README.md"
license = {text = "MIT0"}
authors = []
keywords = []
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.urls]
Repository = "https://github.com/aws-samples/twingraph"

[tool.poetry]
# Poetry-specific configurations that don't have PEP 621 equivalents

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.35.0"
gremlinpython = "^3.7.2"
numpy = "^1.26.0"
docker = "^7.1.0"
celery = "^5.3.0"
flower = "^2.0.0"
simplejson = "^3.19.0"
kombu = "^5.3.0"
pep8 = "^1.7.1"
redis = "^5.0.0"
kubernetes = "^31.0.0"
nest-asyncio = "^1.5.6"
pandas = "^2.2.0"
m2r2 = "^0.3.3.post2"
sphinx-autodoc-typehints = "^2.5.0"
sphinx-markdown-builder = "^0.5.5"
pdoc = "^14.5.1"
pytest = "^8.3.0"
gitpython = "^3.1.43"
aiohttp = "^3.10.0"
certifi = "^2024.7.4"
fastapi = "^0.115.0"
uvicorn = "^0.32.0"
python-socketio = "^5.11.0"
pydantic = "^2.9.0"
opentelemetry-api = "^1.28.0"
opentelemetry-sdk = "^1.28.0"
opentelemetry-instrumentation = "^0.49b0"
opentelemetry-instrumentation-fastapi = "^0.49b0"
opentelemetry-instrumentation-redis = "^0.49b0"
opentelemetry-instrumentation-celery = "^0.49b0"
opentelemetry-instrumentation-httpx = "^0.49b0"
opentelemetry-exporter-otlp = "^1.28.0"
strawberry-graphql = {extras = ["fastapi"], version = "^0.245.0"}

[tool.poetry.group.test.dependencies]
mypy = "^1.13.0"
wemake-python-styleguide = "^0.19.0"
flake8-pytest-style = "^2.0.0"
doc8 = "^1.1.0"
nitpick = "^0.35.0"
safety = "^3.2.0"
pytest = "^8.3.0"
pytest-cov = "^5.0.0"
pytest-randomly = "^3.15.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx-autodoc-typehints = "^2.5.0"
m2r2 = "^0.3"
tomli = "^2.0"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/nitpick-style-wemake.toml"
